# Generated by Django 5.0.6 on 2024-06-19 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('SID', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('supp_name', models.CharField(choices=[('hyundai', 'HYUNDAI'), ('honda', 'HONDA'), ('toyota', 'TOYOTA'), ('volkswagen', 'VOLKSWAGEN')], max_length=20, unique=True)),
                ('country', models.CharField(choices=[('japan', 'JAPAPN'), ('germany', 'GERMANY'), ('southkorea', 'SOUTH KOREA')], max_length=255, unique=True)),
                ('phone', models.IntegerField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cars_Model',
            fields=[
                ('Model', models.CharField(choices=[('bz4x', 'BZ4X'), ('id6', 'ID6'), ('tucson', 'TUCSON'), ('tucson-hybrid', 'TUCSON HYBRID'), ('honda-e', 'HONDA E')], max_length=20, primary_key=True, serialize=False, unique=True)),
                ('Specifications', models.CharField(choices=[('fuel', 'FUEL'), ('electric', 'ELECTRIC')], max_length=20, unique=True)),
                ('Price', models.PositiveIntegerField(max_length=20)),
                ('Year', models.PositiveIntegerField(default='2020', max_length=20)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminstrations.supplier')),
            ],
        ),
    ]
