# Generated by Django 5.0.6 on 2024-06-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars_model',
            name='Price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='cars_model',
            name='Year',
            field=models.CharField(default='2023', max_length=4),
        ),
    ]
