# Generated by Django 5.0.6 on 2024-06-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrations', '0002_alter_cars_model_price_alter_cars_model_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
