# Generated by Django 5.0.6 on 2024-06-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrations', '0003_alter_supplier_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.PositiveIntegerField(),
        ),
    ]
