# Generated by Django 5.0.6 on 2024-06-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Model',
            field=models.CharField(max_length=255),
        ),
    ]
