# Generated by Django 5.0.6 on 2024-06-20 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_remove_order_trackingno'),
        ('orders', '0012_remove_order_user_remove_shipment_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='TrackingNo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='orders.importorder'),
            preserve_default=False,
        ),
    ]
