# Generated by Django 5.0.6 on 2024-06-20 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrations', '0005_alter_cars_model_specifications_and_more'),
        ('finance', '0006_order_trackingno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='TrackingNo',
            new_name='trackingNo',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Model',
        ),
        migrations.AddField(
            model_name='order',
            name='model',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='adminstrations.cars_model'),
            preserve_default=False,
        ),
    ]
