# Generated by Django 5.0.6 on 2024-06-20 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_rename_model_order_model_and_more'),
        ('orders', '0012_remove_order_user_remove_shipment_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='TrackingNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.importorder', unique=True),
        ),
    ]
