# Generated by Django 5.0.6 on 2024-06-20 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrations', '0005_alter_cars_model_specifications_and_more'),
        ('finance', '0010_alter_order_trackingno'),
        ('orders', '0012_remove_order_user_remove_shipment_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('Model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminstrations.cars_model')),
                ('OrderNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.buy', unique=True)),
            ],
        ),
    ]
