# Generated by Django 5.0.6 on 2024-06-20 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='Count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
