# Generated by Django 5.0.6 on 2024-06-20 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0002_alter_inventory_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='Count',
            field=models.IntegerField(default=0),
        ),
    ]
