# Generated by Django 5.0.6 on 2024-06-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Model', models.CharField(default='Anonymous', max_length=100)),
                ('Year', models.CharField(default='2023', max_length=4)),
                ('Price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Name', models.CharField(default='Anonymous', max_length=100)),
                ('Email', models.EmailField(default='example@example.com', max_length=254)),
                ('PhoneNumber', models.CharField(default='000-000-0000', max_length=20)),
                ('Location', models.TextField(default='Unknown Address')),
                ('Color', models.CharField(default='Unspecified', max_length=50)),
                ('Date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
