# Generated by Django 5.0.6 on 2024-06-16 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_buy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='Location',
            field=models.CharField(default='Unknown Address', max_length=50),
        ),
        migrations.AlterField(
            model_name='buy',
            name='PhoneNumber',
            field=models.CharField(default='00-0000-0000', max_length=20),
        ),
    ]
