# Generated by Django 5.0.6 on 2024-06-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_buy_location_alter_buy_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='importOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(default='example@example.com', max_length=254)),
                ('Model', models.CharField(default='Anonymous', max_length=100)),
                ('Specifications', models.CharField(default='Anonymous', max_length=100)),
                ('Color', models.CharField(default='Unspecified', max_length=50)),
                ('Year', models.CharField(default='2023', max_length=4)),
                ('Price', models.PositiveIntegerField()),
                ('Date', models.DateField(blank=True, null=True)),
                ('Count', models.PositiveIntegerField()),
            ],
        ),
    ]
