# Generated by Django 5.0.6 on 2024-06-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_importorder_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='importorder',
            name='Count',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='importorder',
            name='TrackingNo',
            field=models.IntegerField(blank=True, default=0, unique=True),
            preserve_default=False,
        ),
    ]
