# Generated by Django 5.0.6 on 2024-06-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_importorder_count_importorder_trackingno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importorder',
            name='id',
        ),
        migrations.AlterField(
            model_name='importorder',
            name='TrackingNo',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
