# Generated by Django 5.0.6 on 2024-06-19 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrations', '0005_alter_cars_model_specifications_and_more'),
        ('orders', '0009_remove_importorder_id_alter_importorder_trackingno'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importorder',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='importorder',
            name='Price',
        ),
        migrations.RemoveField(
            model_name='importorder',
            name='Specifications',
        ),
        migrations.RemoveField(
            model_name='importorder',
            name='Year',
        ),
        migrations.AlterField(
            model_name='importorder',
            name='Model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminstrations.cars_model'),
        ),
        migrations.AlterField(
            model_name='importorder',
            name='Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
