# Generated by Django 5.0.6 on 2024-06-19 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrations', '0005_alter_cars_model_specifications_and_more'),
        ('orders', '0010_remove_importorder_email_remove_importorder_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='Price',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='Year',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='id',
        ),
        migrations.AddField(
            model_name='buy',
            name='OrderNo',
            field=models.IntegerField(blank=True, default=0, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buy',
            name='Model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminstrations.cars_model'),
        ),
    ]
