# Generated by Django 5.0.6 on 2024-07-01 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_remove_order_user_remove_shipment_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importorder',
            name='Count',
        ),
    ]
