# Generated by Django 5.0.6 on 2024-07-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_remove_importorder_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='importorder',
            name='Count',
            field=models.IntegerField(default=0),
        ),
    ]
